#!/usr/bin/env python3
'''
Pollen Level-2 Post-Training Report Pipeline:
This script performs an automated audit of the Level-2 training outputs. It aggregates 
performance metrics across all taxonomic subgroups and generates visual evidence 
(Heatmaps) for high-confusion species pairs.
Project Architecture:
Pollen_analysis/
├── data/                  # Root data: Initial modelFeatures_1.mat
├── scripts/               # Processing and training scripts
└── output/                # Multi level output hierarchy
    ├── Level1/            # Stage 1: Global clustering
    │   ├── results/       # Input: species_to_cluster_mapping_v1.csv
    │   └── audit/         # Global diagnostic dendrogram plots
    ├── Level2/            # Stage 2: Balanced subgrouping(3-7 subtaxa per cluster)
    │   ├── results/       # Input: Final_Training_Mapping.csv
    │   ├── training/      # Output: ResNet weights (.pth) and raw performance logs(csvs)
    │   └── audit/         # Output: Cluster-specific accuracy reports & heatmaps
    └── Level3/            # Stage 3: Recursive Refinement 
        ├── results/       # Updated_L3_Mapping.csv
        ├── training/      # Refined model outputs
        └── audit/         # Confusion heatmaps and low accuracy diagnosis
Key Functions:
1. Performance Aggregation: Systematically collects all scattered training logs 
to build a high-level summary, allowing an instant overview of which subgroups passed or failed.
2. Cross-Phase Comparison: Compares Baseline vs. Refined performance for each 
subgroup to quantify the impact of data augmentation and learning rate adjustments on model convergence.
3. Conflict Diagnosis: Generates high-resolution confusion heatmap for subgroups failing the 80% accuracy 
threshold. This identifies specific highly similar morphologically inseparable species.
4. Level-3 Decision Support: Provides an evidence-based poor perfotmance list, which helps in
   determinging if proceeding to Level-3 recursive clustering for highly similar taxa is necessary.
Environment Setup:
1. Virtual Environment: activate venv (source venv/bin/activate)
2. Dependencies: torch, torchvision, pandas, scikit-learn, pillow, numpy
Dependencies: pandas, seaborn, matplotlib, numpy
Input Files:
1. Baseline Matrices:./output/Level2/training/results/baseline/baseline_cm_*.csv
   (Generated by the training script during the initial assessment phase)
2. Refined Matrices: ./output/Level2/training/results/refined/refined_cm_*.csv
   (Generated by the training script during the secondary augmentation phase)
Output Files:
1. Global Summary: ./output/Level2/audit/Global_Accuracy_Summary.csv
   (A master table containing metrics for all subgroups)
2. Conflict Heatmaps: ./output/Level2/audit/heatmaps/conflict_diagnosis_sg_*.png
   (Visual evidence of misclassified species, used for Level-3 decision making)
'''
import pandas as pd
# Handling data manipulation of species lists and performance metrics calculation
import seaborn as sns
# Statistical visualization tool for generating confusion matrix heatmaps
import matplotlib.pyplot as plt
#Core plotting engine used to customize figure layouts, titles, and save images
import numpy as np
# Numerical library for matrix trace calculations and summing total predictions
import glob
# File pattern matching utility used to discover all result CSVs across directories
import os
# Path management and handling operating system
#Path where the training script saved the confusion matrix CSVs
BASELINE_DIR = "./output/Level2/training/results/baseline"
REFINED_DIR = "./output/Level2/training/results/refined"
# Path to save the final audit reports and plots
AUDIT_OUT_DIR = "./output/Level2/audit"
# Accuracy threshold which defines subgroups needing Level-3 attention
FAIL_THRESHOLD = 80.0
# Ensure the audit output directory exists,if not it will automatically create one
os.makedirs(AUDIT_OUT_DIR, exist_ok=True)
os.makedirs(os.path.join(AUDIT_OUT_DIR, "heatmaps"), exist_ok=True)
# Main execution function to audit training results and generate visualizations
def generate_reports():
   # Initiate an empty list to store performance metrics
    all_results = []
    # Find all baseline confusion matrix files
    baseline_files=glob.glob(os.path.join(BASELINE_DIR, "baseline_cm_*.csv"))
    # Print the count to console
    print(f"Found {len(baseline_files)} subgroup results.")
    # Iterate through baseline files
    for f in baseline_files:
        # Extract subgroup id from filename (e.g., '1.1' from 'baseline_cm_1.1.csv')
        sg_id=os.path.basename(f).split('_')[-1].replace('.csv', '')
        # Load the confusion matrix
        # index_col=0 ensures species names are used as row labels
        df_base=pd.read_csv(f, index_col=0)
        # Calculate baseline metrics
        total_samples = np.sum(df_base.values)
        # Calculate the trace (sum of the main diagonal) to count all correct predictions
        correct_preds = np.trace(df_base.values)
        base_acc=(correct_preds/total_samples*100) if total_samples > 0 else 0
        # Check if a refined training version for the current subgroup
        refined_path=os.path.join(REFINED_DIR,f"refined_cm_{sg_id}.csv")
        # Initialize refined accuracy as None to handle groups that only ran baseline
        refined_acc=None
        # Default the final data source to baseline for heatmaps unless refinement is found
        final_df=df_base 
        # Determine if the refinement stage was triggered for this specific id
        if os.path.exists(refined_path):
            # Load the refined confusion matrix from the secondary results directory
            df_ref=pd.read_csv(refined_path, index_col=0)
            #Recalculate the accuracy percentage using the refined matrix values
            refined_acc=(np.trace(df_ref.values)/np.sum(df_ref.values)*100)
            # Update the heatmap source to the refined data for a more accurate conflict diagnosis
            final_df=df_ref
        # Determine current status
        current_max_acc=refined_acc if refined_acc is not None else base_acc
        status = "PASS" if current_max_acc >= FAIL_THRESHOLD else "FAIL (Needs L3)"
        # Append data for the global summary table
        all_results.append({
            'SubGroup_ID':sg_id,
            'Species_Count':len(df_base.index),
            'Total_Samples':total_samples,
            'Baseline_Acc%':round(base_acc, 2),
            'Refined_Acc%':round(refined_acc, 2) if refined_acc else "N/A",
            'Final_Best_Acc%':round(current_max_acc, 2),
            'Status': status
        })
        # Visualization
        # Generate heatmaps for groups that fail the threhold and need further Level-3 cutoff refinement
        if True:
            plt.figure(figsize=(10, 8))
            # Create heatmap: annot=True shows raw counts, cmap='YlGnBu' provides clear contrast
            sns.heatmap(final_df, annot=True, fmt='d', cmap='YlGnBu', cbar=True)
            plt.title(f"Confusion Analysis: SubGroup {sg_id}\nFinal Accuracy: {current_max_acc:.1f}%")
            plt.xlabel("Predicted Species")
            plt.ylabel("True Species")
            plt.xticks(rotation=45, ha='right')
            plt.tight_layout()
            # Save plot for Level-3 evidence reporting
            plot_name = f"conflict_diagnosis_sg_{sg_id}.png"
            plt.savefig(os.path.join(AUDIT_OUT_DIR, "heatmaps", plot_name))
            # Close figure to free up memory
            plt.close() 
    # Finalize the Global Summary Report
    summary_df=pd.DataFrame(all_results)
    # Sort by subgroup id
    summary_df['sort_key']=summary_df['SubGroup_ID'].apply(lambda x: [int(i) for i in str(x).split('.')])
    summary_df=summary_df.sort_values('sort_key').drop('sort_key', axis=1)
    # Export to CSV f
    summary_path=os.path.join(AUDIT_OUT_DIR, "Global_Accuracy_Summary.csv")
    summary_df.to_csv(summary_path, index=False)
    print("-" * 50)
    print(f"Audit Complete!")
    print(f"Summary Table: {summary_path}")
    print(f"Diagnostic Heatmaps: {os.path.join(AUDIT_OUT_DIR, 'heatmaps')}")
    print("-" * 50)
if __name__ == "__main__":
    generate_reports()