#!/usr/bin/env python3
"""
Pollen Level-3 Data Pipeline:
This script processes the morphological clusters generated by the Level-2 
cutoff thresholds. It initializes specialized training environments for 
Level-3 prototypes, enabling the neural network to focus on fine-grained features 
required to distinguish between highly similar species within each subgroup.
Key Functions:
1. Adaptive Filtering: Automatically cross-references the CSV species mapping 
with physical image folders. If species images are missing due to the subset data, 
the script gracefully skips them without crashing.
2. Automated Data Cleaning: Uses pattern-recognition to dynamically ignore any 
species labeled with an 'x' (taxonomic uncertainty) or 'zz' (environmental noise) 
in the mapping file. This ensures the model only focuses on high-confidence 
biological samples.
3. Class Balancing (NtrIm=1000): The script limits each pollen species to a maximum of 1000 images. 
By capping over-represented species, the model provides equal weight to both common and rare species, 
effectively controlling model bias.
4. Splitting Validation (validate=1): Uses a randomized 90/10 split (Train/Val) 
to calculate accuracy metrics and confusion matrices that reflect the model's 
true ability to generalize to new pollen samples.
Usage:
1. Environment Setup:
Before execution, ensure the Python virtual environment is activated: source venv/bin/activate
2. Direct Execution:
This script is designed as the primary entry point for Level-3 analysis. 
It should be executed directly to trigger the full training sequence: python3 scripts/main_pipeline.py
"""
import os             
# Path management and interacting with operating system
import random          
# Random sampling to select a representative subset for training
import pandas as pd    
# Handling data manipulation of species lists and performance metrics calculation
import torch           
# The core Deep Learning framework (PyTorch) for ResNet18 neural network. 
from torch.utils.data import Dataset, DataLoader 
# Dataset: Defines the logic for mapping individual raw pollen images to their verified species labels
# DataLoader: Automates the data flow by organizing images into structured batches
from torchvision import transforms 
# A toolkit for image augmentation to help the model learn finer features
from PIL import Image 
# For opening and processing various image formats like JPG and PNG
# Define a custom dataset class inheriting from the PyTorch Dataset base class
class SubGroupPollenDataset(Dataset):
    # Initialize the dataset with image file paths, category labels(taxon indices), and optional transforms
    def __init__(self, image_paths, taxon_indices, transform=None):
        # Pair each image path with its corresponding label into a list of tuples
        self.samples=list(zip(image_paths, taxon_indices))
        # Store the transformation pipeline to be applied during data loading
        self.transform=transform
    # Return the total number of sample images in the dataset
    def __len__(self):
        # Use the built-in len() function to get the size of the samples list
        return len(self.samples)
    # Retrieve a single data sample from the dataset at the given index
    def __getitem__(self, idx):
        # Unpack the image path and corresponding label from the samples list
        img_path, taxon_indices=self.samples[idx]
        try:
            # Load the image and ensure it is in RGB color mode
            image = Image.open(img_path).convert('RGB')
        except Exception as e:
            # Return a black placeholder tensor if the image file is corrupted or missing
            return torch.zeros((3, 224, 224)), taxon_indices
        # Apply transformations(resizing, normalization, or data argumentation if needed.)
        if self.transform:
            image = self.transform(image)
        # Return the processed image and its corresponding label as a pair  
        return image, taxon_indices
# Define a function to prepare and return data loaders for batch processing
def get_pollen_dataloaders(
    mapping_csv,           
    # Path to the CSV file containing image metadata and labels
    target_subgroup,       
    # The specific subgroup category to filter and load
    image_dir,             
    # The root directory of image files 
    batch_size=16,         
    # Number of samples per training batch
    include_uncertain=False, 
    # Toggle to include/exclude species marked with 'x' or 'group'
    include_garbage=False, 
    # Toggle to include/exclude 'zz' prefixed environmental noise
    max_imgs_per_class=1000 
    # Limit the number of images per class to prevent class imbalance
):
    # Initialize an audit dictionary to track the automated cleaning statistics for reporting
    audit={'csv_total': 0,'auto_lumped': 0,'auto_garbage': 0, 'missing_disk': 0, 'valid_final': 0}
    # Load the mapping CSV file and ensure SubGroup_ID is read as a string to preserve format
    df=pd.read_csv(mapping_csv, dtype={'SubGroup_ID': str})
    # Extract all species belonging to the current subgroup and save them into a new table
    subgroup_df=df[df['SubGroup_ID']==str(target_subgroup)].copy()
    # Check if the filtered dataframe is not empty
    if subgroup_df.empty:
        raise ValueError(f"SubGroup '{target_subgroup}' not found in the CSV.")
    # Extract unique species names and record the starting count for the audit dictionary
    expected_species = sorted(subgroup_df['Species_Name'].unique())
    # Record the initial number of species classes to check if cleaning process leads to loss of species due to image numbers
    audit['csv_total']=len(expected_species)
    # Check the existence of the source image directory before proceeding
    if not os.path.exists(image_dir):
        # Raise error if path is invalid
        raise FileNotFoundError(f"Root directory '{image_dir}' not found")
    # Create a mapping of lowercase folder names to their actual  names in image folder for robust matching
    actual_folders={file.strip().lower(): file for file in os.listdir(image_dir) if os.path.isdir(os.path.join(image_dir, file))}}
    # Initialize a list for species after cleaning process and found in csv and image folder
    valid_species = [] 
    # Automatic screen data and match CSV species names against physical image folders to link taxon ids with raw images
    for species in expected_species:
        # Screen 'x' or 'group' markers indicating taxonomic uncertainty
        is_uncertain=any(marker in species.lower() for marker in [' x',' x ','group','-group'])
        if not include_uncertain and is_uncertain:
            # Update audit tracker for dynamically identified lumped/uncertain classes
            audit['auto_lumped']+= 1
            continue
        # Screen 'zz' prefix or 'garbage' keyword indicating pollutants/debris
        is_garbage=species.lower().strip().startswith('zz') or 'garbage' in species.lower()
        if not include_garbage and is_garbage:
            # Update audit counter for noise classes
            audit['auto_garbage'] += 1
            continue
        # Standardize species name for robust folder matching (removes family prefixes and spaces)
        target_clean=species.replace("SAPI ", "").strip().lower().replace(" ", "").replace("_", "")
        # Check and match standardize CSV name against standarized image folder names
        match_found = False
        for folder_key, original_folder in actual_folders.items():
            # Remove whitespaces and prefixes
            folder_clean=folder_key.replace(" ", "").replace("_", "")
            # Append the successful match for csv species name and image species name and break the inner loop
            if target_clean==folder_clean or folder_clean in target_clean:
                valid_species.append((species, original_folder))
                match_found=True
                break
        # Track species present in mapping but absent in image folder
        if not match_found:
            audit['missing_disk']+=1
    # Print a comprehensive data audit summary 
    print(f"\n"+"="*60)
    print(f"Data audit:SubGroup {target_subgroup}")
    print(f"Species in CSV:{audit['csv_total']}")
    print(f"Auto-Filtered (x):{audit['auto_lumped']}")
    print(f"Auto-Filtered (zz):{audit['auto_garbage']}")
    print(f"Missing in Image Folder: {audit['missing_disk']}")
    print(f"Validated for Training: {len(valid_species)}")
    print("="*60 + "\n")
    # Ensure the subgroup contains at least 2 distinct species classes
    if len(valid_species)<2:
        raise ValueError(f"SubGroup '{target_subgroup}' lacks sufficient classes after automated cleaning.")
    #Create a lookup dictionary where each species name(extracted from the validated (species, folder) pairs) as key to a unique taxon id value
    #Enumerate automatically generates the index starting from 0, assigned as the value
    species_names=[item[0] for item in valid_species]
    label_map={species: idx for idx, species in enumerate(species_names)}
    # Initialize lists for the partitioned dataset (90% training, 10% validation)
    # paths store the raw image locations, labels store the corresponding taxon ids
    train_paths, train_labels, val_paths, val_labels=[], [], [], []
    # Iterate through each validated pair of species names and their corresponding physical image folder
    for original_species, physical_folder in valid_species:
        # Construct the absolute file path by joining the root image directory with the specific species folder
        species_folder = os.path.join(image_dir, physical_folder)
        # Search for valid image extensions like png, jpg,jpeg
        img_names = [f for f in os.listdir(species_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]   
        # Randomly shuffle the image list to ensure unbiased sample selection during the subsequent 90/10 data split
        random.shuffle(img_names)
        #Cap the number of images per species to 1000
        if len(img_names)>max_imgs_per_class:
            img_names=img_names[:max_imgs_per_class]
        # Calculate indices for 90% training and 10% validation
        split_idx = int(len(img_names)*0.9)
        if split_idx==0 and len(img_names) > 0: 
            split_idx=1 
        train_imgs=img_names[:split_idx]
        val_imgs=img_names[split_idx:]
        local_label=label_map[original_species]   
        # Finalize path lists for training and validation sets
        train_paths.extend([os.path.join(species_folder, f) for f in train_imgs])
        train_labels.extend([local_label]*len(train_imgs))
        val_paths.extend([os.path.join(species_folder, f) for f in val_imgs])
        val_labels.extend([local_label]*len(val_imgs))
    # Define Data Augmentation (Training) and Normalization (Validation)
    train_transforms=transforms.Compose([
        transforms.Resize((256, 256)),               
        transforms.RandomResizedCrop(224, scale=(0.8, 1.0)), 
        transforms.RandomHorizontalFlip(p=0.5),      
        transforms.RandomVerticalFlip(p=0.5),        
        transforms.RandomRotation(degrees=180),      
        transforms.ColorJitter(brightness=0.2, contrast=0.2), 
        transforms.ToTensor(),                       
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    val_transforms=transforms.Compose([
        transforms.Resize((256, 256)),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    # Wrap data into PyTorch Dataset and DataLoader instances
    train_ds=SubGroupPollenDataset(train_paths, train_labels, transform=train_transforms)
    val_ds=SubGroupPollenDataset(val_paths, val_labels, transform=val_transforms)
    train_loader=DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=4)
    val_loader=DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=4)
    return train_loader, val_loader, species_names